
import Footer from "./components/footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import 'bootstrap-icons/font/bootstrap-icons.min.css'; 
import 'animate.css';
import BootstrapClient from "./components/bootstrapClient";

            

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="th">
      <body>
        {children}
        <Navbar/>
        <Footer/>
      </body>
      <BootstrapClient/>
    </html>
  );
}